Implemented: new message if user searches for a keyword that not matches with any result in completed, open and progress view
hotwax/fulfillment-pwa pull request #217
Opened 2023-07-25 08:48 UTC by sanskar345

### Related Issues

Closes #138

### Short Description and Why It's Useful

"No results found for <keyword>. Try searching In Progress or Completed tab instead.
If you still can't find what you're looking for, try switching stores." message is displayed in the tab if the user search keyword does not match any result.

### Screenshots of Visual Changes before/after (If There Are Any)

![message](https://github.com/hotwax/fulfillment-pwa/assets/67117461/886b45ac-faf9-4865-8773-3f62efb911f1)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

2023-07-25 09:17 UTC, ymaheshwari1 commented on src/views/InProgress.vue
> +        <div v-if="searchedQuery != ''">{{ $t( `No results found for ${searchedQuery}. Try searching In Open or Completed tab instead.` ) }}</div>
```suggestion
        <div v-if="searchedQuery != ''">{{ $t( `No results found for ${searchedQuery}. Try searching in Open or Completed tab instead.` ) }}</div>
```

2023-07-25 09:17 UTC, ymaheshwari1 commented on src/views/Completed.vue
> +        <div v-if="searchedQuery != ''">{{ $t( `No results found for ${searchedQuery}. Try searching In Progress or Open tab instead.` ) }}</div>
Add internationalization.

2023-07-25 09:56 UTC, sanskar345 commented on src/views/Completed.vue
> +        <div v-if="searchedQuery != ''">{{ $t( `If you still can't find what you're looking for, try switching stores.` ) }}</div>
done

2023-07-25 09:57 UTC, sanskar345 commented on src/views/Completed.vue
> +        <div v-if="searchedQuery != ''">{{ $t( `No results found for ${searchedQuery}. Try searching In Progress or Open tab instead.` ) }}</div>
done

2023-07-26 09:08 UTC, ymaheshwari1 requested changes

2023-07-26 09:08 UTC, ymaheshwari1 commented on src/views/Completed.vue
> +        <p v-if="searchedQuery != ''">{{ $t( `No results found for`)}}{{ " " + searchedQuery}}{{ $t(`. Try searching In Progress or Open tab instead.`)}} <br> {{ $t( `If you still can't find what you
Use a single string for the message.

2023-07-28 10:51 UTC, ymaheshwari1 requested changes

2023-07-28 10:51 UTC, ymaheshwari1 commented on src/locales/en.json
> +  " doesn't have any outstanding orders right now.": "{facilityName} doesn't have any outstanding orders right now.",
```suggestion
  "doesn't have any outstanding orders right now.": "{facilityName} doesn't have any outstanding orders right now.",
```

2023-07-28 10:51 UTC, ymaheshwari1 commented on src/locales/en.json
>    " doesn't have any orders in progress right now.": " doesn't have any orders in progress right now.",
Update the error handling for completed and in progress page as well.

2023-07-28 10:51 UTC, ymaheshwari1 commented on src/views/OpenOrders.vue
> +      return this.searchedQuery === '' ? this.$t(" doesn't have any outstanding orders right now.", { facilityName: this.currentFacility.name }) : this.$t( "No results found for . Try searching In Pr
```suggestion
      return this.searchedQuery === '' ? this.$t("doesn't have any outstanding orders right now.", { facilityName: this.currentFacility.name }) : this.$t( "No results found for . Try searching In Progress or Completed tab instead. If you still can't find what you're looking for, try switching stores.", { searchedQuery: this.searchedQuery, lineBreak: '<br />' })
```

2023-07-31 08:45 UTC, ymaheshwari1 approved these changes

2023-08-01 06:42 UTC, merged