Box Type change functionality in progress tab
hotwax/fulfillment-pwa pull request #222
Opened 2023-07-27 09:11 UTC by sanskar345

### Related Issues

Closes #221

### Short Description and Why It's Useful

Added box type change functionality in the progress tab in package chips (added ion select to change the box type).

### Screenshots of Visual Changes before/after (If There Are Any)

![eee](https://github.com/hotwax/fulfillment-pwa/assets/67117461/8ce464d4-6c1e-44c5-b2d5-e2a1bf9e6365)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

2023-08-09 12:35 UTC, ymaheshwari1 requested changes

2023-08-09 12:35 UTC, ymaheshwari1 commented on src/views/InProgress.vue
> +      if(packageType === undefined){
Also if we don't find any value we should display the default value

2023-08-10 05:21 UTC, sanskar345 commented on src/views/InProgress.vue
> +      if(packageType === undefined){
done

2023-08-14 12:44 UTC, ymaheshwari1 requested changes

2023-08-14 12:44 UTC, ymaheshwari1 commented on src/views/InProgress.vue
> +    onBoxTypeChange(value: string, shipmentPackage: any, order: any){
```suggestion
    updateShipmentBoxType(value: string, shipmentPackage: any, order: any) {
```

2023-08-14 12:44 UTC, ymaheshwari1 commented on src/views/InProgress.vue
> +    getShipmentPackageType(shipmentPackage: any, order: any) {
We can move this logic in the action itself.

2023-08-14 12:44 UTC, ymaheshwari1 commented on src/views/InProgress.vue
> +      let packageType = '';
We can set the default value for the packageType initially and can remove the extra nested if condition.
```suggestion
      let packageType = order.shipmentBoxTypeByCarrierParty[shipmentPackage.carrierPartyId][0];
```

2023-10-12 09:28 UTC, merged