Update es.json
hotwax/fulfillment-pwa pull request #298
Opened 2023-10-11 16:10 UTC by Samux0112

I am samuel from ADOC

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

2023-10-11 16:12 UTC, Samux0112 reviewed
ok

2023-10-12 14:27 UTC, ymaheshwari1 requested changes
Hi @Samux0112 
Thanks for providing the translations.

Please check my comments once.

2023-10-12 14:27 UTC, ymaheshwari1 commented on src/locales/es.json
> +  "is identified as unfulfillable. other containing this product will be unassigned from this store and sent to be rebrokered.": "{ productName } se identifica como no cumplible.  { espacio } { order
Please revert the translation for variables. All those entries that are in `{}`

2023-10-12 14:27 UTC, ymaheshwari1 commented on src/locales/es.json
> -  "Update mapping": "Update mapping",
Please provide the translations for labels those are missing.

2023-10-12 14:27 UTC, ymaheshwari1 commented on src/locales/es.json
> +  "Tax Exempt": "Exento de impuestos",
Please remove the extra entries from the file.

2023-10-25 06:53 UTC, ymaheshwari1 commented
Closing as handled in https://github.com/hotwax/fulfillment-pwa/pull/333

2023-10-25 06:53 UTC, closed without merging