Implemented: Shift-JIS encoding conversion for export packed orders feed.
hotwax/fulfillment-pwa pull request #559
Opened 2024-05-22 11:02 UTC by Nishtha-Jain-1119

### Related Issues

Closes #

### Short Description and Why It's Useful

Added support to convert the encoding into Shift-JIS format for export packed orders feed when user locale is Japanese.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

2024-05-22 11:09 UTC, ymaheshwari1 requested changes

2024-05-22 11:09 UTC, ymaheshwari1 commented on src/utils/index.ts
> +import Encoding from 'encoding-japanese';
Add this package in package.json file and also add types for the same `types/encoding-japanese`.

2024-05-22 11:09 UTC, ymaheshwari1 commented on src/views/DownloadPackedOrders.vue
> +              <ion-icon color="success" :icon="addCircleOutline" />
Revert all this unwanted changes, like removing a space or adding a new space etc

2024-05-22 12:47 UTC, merged

2024-05-23 13:45 UTC, Adameddy26 commented
Changes verified and working fine in release v2.4.3. File type shown is us-ascii which is expected.